
import { User, UserRole, Project, Task, Notification, FormTemplate, Plan, FieldIssue, RFI, PlanFolder } from './types';

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Marcus Jensen',
  role: UserRole.FOREMAN,
  avatar: 'https://picsum.photos/id/1012/200/200'
};

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Eaglewood Retail Center',
    location: '290 S Orchard Dr, North Salt Lake, UT 84054',
    status: 'ACTIVE',
    budget: 2800000,
    spent: 1820000,
    progress: 65,
    startDate: '2024-06-01',
    endDate: '2025-04-30'
  },
  {
    id: 'p2',
    name: 'Orchard Plaza East Renovation',
    location: '20-50 S Orchard Dr, North Salt Lake, UT 84054',
    status: 'ACTIVE',
    budget: 1450000,
    spent: 319000,
    progress: 22,
    startDate: '2024-09-15',
    endDate: '2025-08-20'
  },
  {
    id: 'p3',
    name: 'Legacy Parkway Trail Extension',
    location: 'Legacy Parkway & Center St, North Salt Lake, UT',
    status: 'PLANNING',
    budget: 4200000,
    spent: 84000,
    progress: 5,
    startDate: '2025-03-01',
    endDate: '2026-06-30'
  }
];

export const PLAN_FOLDERS: PlanFolder[] = [
  { id: 'arch', name: 'Architectural', count: 14 },
  { id: 'struct', name: 'Structural', count: 8 },
  { id: 'elec', name: 'Electrical', count: 5 },
  { id: 'mech', name: 'Mechanical', count: 6 },
];

export const PLANS: Plan[] = [
  {
    id: 'pl1',
    projectId: 'p1',
    folderId: 'arch',
    name: 'A-101 Retail Ground Floor Plan',
    version: 'v2.1',
    imageUrl: 'https://images.unsplash.com/photo-1599700403969-fcc35f4f04c5?q=80&w=2574&auto=format&fit=crop',
    uploadDate: '2024-10-10'
  },
  {
    id: 'pl2',
    projectId: 'p1',
    folderId: 'elec',
    name: 'E-201 Electrical Rough-in',
    version: 'v1.0',
    imageUrl: 'https://images.unsplash.com/photo-1630327773229-9e8e25d6b4a3?q=80&w=2670&auto=format&fit=crop',
    uploadDate: '2024-10-12'
  }
];

export const FIELD_ISSUES: FieldIssue[] = [
  {
    id: 'fi1',
    planId: 'pl1',
    x: 45,
    y: 30,
    status: 'OPEN',
    priority: 'HIGH',
    category: 'Quality',
    description: 'HVAC supply duct conflicts with steel beam at Grid C-4. Coordinate with Hughes GC for resolution.',
    assignedTo: 'Derek Sorensen',
    dueDate: '2024-12-15'
  },
  {
    id: 'fi2',
    planId: 'pl1',
    x: 72,
    y: 65,
    status: 'RESOLVED',
    priority: 'MEDIUM',
    category: 'Punch List',
    description: 'Missing 20A outlet at drive-thru window per tenant specs.',
    assignedTo: 'Cody Rasmussen'
  }
];

export const RFIS: RFI[] = [
  {
    id: 'rfi1',
    projectId: 'p1',
    number: '007',
    subject: 'Fire Sprinkler Head Spacing in Suite 102',
    question: 'Drawing FP-201 shows sprinkler heads at 12\' spacing but the tenant improvement plans for Eaglewood Retail Suite 102 include a dropped ceiling at 9\'. Please clarify if additional heads are required per Davis County Fire Authority standards.',
    status: 'OPEN',
    costImpact: 'Potential $4,200',
    scheduleImpact: '3 Days',
    assignedTo: 'Brent Kimball, PE - Spectrum Engineers',
    dueDate: '2024-12-10'
  },
  {
    id: 'rfi2',
    projectId: 'p1',
    number: '006',
    subject: 'ADA Ramp Slope at Main Entrance',
    question: 'Civil drawings show 8.5% slope on the ADA ramp approach from the Orchard Drive sidewalk. Utah accessibility code requires max 8.33%. Confirm if regrading is required or if variance has been obtained from North Salt Lake Building Dept.',
    status: 'CLOSED',
    costImpact: '$1,800',
    scheduleImpact: '1 Day',
    assignedTo: 'Civil West Engineering',
    dueDate: '2024-11-20'
  }
];

export const TASKS: Task[] = [
  {
    id: 't1',
    projectId: 'p1',
    name: 'Site Preparation & Grading',
    startDate: '2024-11-01',
    durationDays: 8,
    progress: 100,
    assignedCrew: 6,
    requiredCrew: 6,
    budget: 45000,
    spent: 43500,
    status: 'COMPLETED',
    predecessors: [],
    isMilestone: false,
    phase: 'Site Work',
    actualStartDate: '2024-11-01',
    actualEndDate: '2024-11-08',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't2',
    projectId: 'p1',
    name: 'Foundation Excavation',
    startDate: '2024-11-09',
    durationDays: 5,
    progress: 100,
    assignedCrew: 8,
    requiredCrew: 8,
    budget: 62000,
    spent: 58900,
    status: 'COMPLETED',
    predecessors: [{ taskId: 't1', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Foundation',
    actualStartDate: '2024-11-09',
    actualEndDate: '2024-11-13',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't3',
    projectId: 'p1',
    name: 'Foundation Pour Complete',
    startDate: '2024-11-14',
    durationDays: 1,
    progress: 100,
    assignedCrew: 0,
    requiredCrew: 0,
    budget: 0,
    spent: 0,
    status: 'COMPLETED',
    predecessors: [{ taskId: 't2', type: 'FS', lagDays: 0 }],
    isMilestone: true,
    phase: 'Foundation',
    actualStartDate: '2024-11-14',
    actualEndDate: '2024-11-14',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't4',
    projectId: 'p1',
    name: 'Structural Steel Erection',
    startDate: '2024-11-15',
    durationDays: 14,
    progress: 80,
    assignedCrew: 5,
    requiredCrew: 6,
    budget: 185000,
    spent: 156000,
    status: 'IN_PROGRESS',
    predecessors: [{ taskId: 't3', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Structure',
    actualStartDate: '2024-11-15',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't5',
    projectId: 'p1',
    name: 'Underground Plumbing Rough-in',
    startDate: '2024-11-18',
    durationDays: 7,
    progress: 60,
    assignedCrew: 4,
    requiredCrew: 4,
    budget: 38000,
    spent: 22800,
    status: 'IN_PROGRESS',
    predecessors: [{ taskId: 't2', type: 'FS', lagDays: 3 }],
    isMilestone: false,
    phase: 'MEP',
    actualStartDate: '2024-11-18',
    priority: 'MEDIUM',
    isOnCriticalPath: false,
    slack: 5
  },
  {
    id: 't6',
    projectId: 'p1',
    name: 'Concrete Slab - Building B',
    startDate: '2024-11-25',
    durationDays: 5,
    progress: 20,
    assignedCrew: 8,
    requiredCrew: 8,
    budget: 72000,
    spent: 14400,
    status: 'IN_PROGRESS',
    predecessors: [{ taskId: 't5', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Foundation',
    actualStartDate: '2024-11-25',
    priority: 'HIGH',
    isOnCriticalPath: false,
    slack: 3
  },
  {
    id: 't7',
    projectId: 'p1',
    name: 'Steel Erection Complete',
    startDate: '2024-11-29',
    durationDays: 1,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 0,
    budget: 0,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't4', type: 'FS', lagDays: 0 }],
    isMilestone: true,
    phase: 'Structure',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't8',
    projectId: 'p1',
    name: 'Metal Deck Installation',
    startDate: '2024-11-30',
    durationDays: 8,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 6,
    budget: 67000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't7', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Structure',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't9',
    projectId: 'p1',
    name: 'Metal Stud Framing',
    startDate: '2024-12-05',
    durationDays: 20,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 10,
    budget: 94000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't8', type: 'SS', lagDays: 3 }],
    isMilestone: false,
    phase: 'Framing',
    priority: 'MEDIUM',
    isOnCriticalPath: false,
    slack: 5
  },
  {
    id: 't10',
    projectId: 'p1',
    name: 'Electrical Rough-in',
    startDate: '2024-12-10',
    durationDays: 15,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 5,
    budget: 82000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't9', type: 'SS', lagDays: 5 }],
    isMilestone: false,
    phase: 'MEP',
    priority: 'MEDIUM',
    isOnCriticalPath: false,
    slack: 8
  },
  {
    id: 't11',
    projectId: 'p1',
    name: 'HVAC Ductwork Installation',
    startDate: '2024-12-12',
    durationDays: 18,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 6,
    budget: 95000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't9', type: 'SS', lagDays: 7 }],
    isMilestone: false,
    phase: 'MEP',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't12',
    projectId: 'p1',
    name: 'Storefront Glazing Installation',
    startDate: '2024-12-20',
    durationDays: 12,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 4,
    budget: 128000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't8', type: 'FS', lagDays: 5 }],
    isMilestone: false,
    phase: 'Exterior',
    priority: 'MEDIUM',
    isOnCriticalPath: false,
    slack: 10
  },
  {
    id: 't13',
    projectId: 'p1',
    name: 'Roofing Installation',
    startDate: '2024-12-15',
    durationDays: 10,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 8,
    budget: 156000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't8', type: 'FS', lagDays: 7 }],
    isMilestone: false,
    phase: 'Exterior',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't14',
    projectId: 'p1',
    name: 'Building Dried In',
    startDate: '2024-12-25',
    durationDays: 1,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 0,
    budget: 0,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't13', type: 'FS', lagDays: 0 }, { taskId: 't12', type: 'FS', lagDays: 0 }],
    isMilestone: true,
    phase: 'Exterior',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't15',
    projectId: 'p1',
    name: 'Drywall Installation',
    startDate: '2024-12-26',
    durationDays: 15,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 12,
    budget: 78000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't14', type: 'FS', lagDays: 0 }, { taskId: 't10', type: 'FS', lagDays: 0 }, { taskId: 't11', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Finishes',
    priority: 'MEDIUM',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't16',
    projectId: 'p1',
    name: 'Paint & Finishes',
    startDate: '2025-01-10',
    durationDays: 12,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 8,
    budget: 45000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't15', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Finishes',
    priority: 'MEDIUM',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't17',
    projectId: 'p1',
    name: 'Flooring Installation',
    startDate: '2025-01-15',
    durationDays: 10,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 6,
    budget: 92000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't16', type: 'SS', lagDays: 5 }],
    isMilestone: false,
    phase: 'Finishes',
    priority: 'MEDIUM',
    isOnCriticalPath: false,
    slack: 3
  },
  {
    id: 't18',
    projectId: 'p1',
    name: 'Final Inspections',
    startDate: '2025-01-25',
    durationDays: 5,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 2,
    budget: 5000,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't16', type: 'FS', lagDays: 3 }, { taskId: 't17', type: 'FS', lagDays: 0 }],
    isMilestone: false,
    phase: 'Closeout',
    priority: 'HIGH',
    isOnCriticalPath: true,
    slack: 0
  },
  {
    id: 't19',
    projectId: 'p1',
    name: 'Substantial Completion',
    startDate: '2025-01-30',
    durationDays: 1,
    progress: 0,
    assignedCrew: 0,
    requiredCrew: 0,
    budget: 0,
    spent: 0,
    status: 'NOT_STARTED',
    predecessors: [{ taskId: 't18', type: 'FS', lagDays: 0 }],
    isMilestone: true,
    phase: 'Closeout',
    priority: 'CRITICAL',
    isOnCriticalPath: true,
    slack: 0
  }
];

export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'ALERT', message: 'Davis County inspection scheduled for Dec 5th - prep required', timestamp: '2h ago' },
  { id: 'n2', type: 'INFO', message: 'Snow forecast Wednesday - Concrete pour may need rescheduling', timestamp: '5h ago' },
  { id: 'n3', type: 'SUCCESS', message: 'PO #8847 approved by Acme Construction procurement', timestamp: '1d ago' },
  { id: 'n4', type: 'ALERT', message: 'Staker Parson delivery arriving 7:00 AM - Orchard Dr access', timestamp: '3h ago' }
];

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    id: 'f1',
    title: 'Daily Safety Inspection',
    fields: [
      { id: 'fl1', type: 'text', label: 'Inspector Name', required: true },
      { id: 'fl2', type: 'yesno', label: 'PPE Check Passed?', required: true },
      { id: 'fl3', type: 'photo', label: 'Site Overview Photo', required: true },
      { id: 'fl4', type: 'text', label: 'Hazards Identified', required: false },
      { id: 'fl5', type: 'signature', label: 'Foreman Signature', required: true }
    ]
  },
  {
    id: 'f2',
    title: 'Material Delivery Log',
    fields: [
      { id: 'm1', type: 'text', label: 'Vendor Name', required: true },
      { id: 'm2', type: 'photo', label: 'Packing Slip', required: true },
      { id: 'm3', type: 'yesno', label: 'Damaged Goods?', required: true },
      { id: 'm4', type: 'text', label: 'PO Number', required: true }
    ]
  },
  {
    id: 'f3',
    title: 'Concrete Pour Report',
    fields: [
      { id: 'c1', type: 'text', label: 'Pour Location / Grid', required: true },
      { id: 'c2', type: 'number', label: 'Cubic Yards Placed', required: true },
      { id: 'c3', type: 'text', label: 'Concrete Supplier', required: true },
      { id: 'c4', type: 'text', label: 'Batch Ticket Numbers', required: true },
      { id: 'c5', type: 'photo', label: 'Slump Test Photo', required: true },
      { id: 'c6', type: 'signature', label: 'QC Inspector Signature', required: true }
    ]
  }
];
