import React, { useState, useRef } from 'react';
import { Plus, FileText, Camera, Send, ChevronRight, X, Download, Check, Trash2 } from 'lucide-react';
import { FORM_TEMPLATES, CURRENT_USER } from '../constants';
import { FormTemplate } from '../types';

interface FormSubmission {
  id: string;
  templateId: string;
  templateTitle: string;
  submittedBy: string;
  submittedAt: Date;
  data: Record<string, any>;
}

// Initial submissions data
const INITIAL_SUBMISSIONS: FormSubmission[] = [
  {
    id: 'sub1',
    templateId: 'f1',
    templateTitle: 'Daily Safety Inspection',
    submittedBy: CURRENT_USER.name,
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    data: { inspectorName: CURRENT_USER.name, ppeCheck: 'yes', hazards: 'None identified' }
  },
  {
    id: 'sub2',
    templateId: 'f2',
    templateTitle: 'Material Delivery Log',
    submittedBy: 'Derek Sorensen',
    submittedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    data: { vendorName: 'Staker Parson', damagedGoods: 'no', poNumber: 'PO-8847' }
  },
  {
    id: 'sub3',
    templateId: 'f3',
    templateTitle: 'Concrete Pour Report',
    submittedBy: 'Cody Rasmussen',
    submittedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    data: { pourLocation: 'Grid B-4', cubicYards: 45, concreteSupplier: 'Geneva Rock' }
  }
];

export const Forms: React.FC = () => {
  const [activeForm, setActiveForm] = useState<string | null>(null);
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [submissions, setSubmissions] = useState<FormSubmission[]>(INITIAL_SUBMISSIONS);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [photos, setPhotos] = useState<Record<string, string>>({});
  const [signatures, setSignatures] = useState<Record<string, boolean>>({});
  const fileInputRefs = useRef<Record<string, HTMLInputElement | null>>({});

  const formatTimeAgo = (date: Date) => {
    const seconds = Math.floor((new Date().getTime() - date.getTime()) / 1000);
    if (seconds < 60) return 'Just now';
    if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`;
    return `${Math.floor(seconds / 86400)} days ago`;
  };

  const handleFieldChange = (fieldId: string, value: any) => {
    setFormData(prev => ({ ...prev, [fieldId]: value }));
  };

  const handlePhotoUpload = (fieldId: string, e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setPhotos(prev => ({ ...prev, [fieldId]: reader.result as string }));
        setFormData(prev => ({ ...prev, [fieldId]: file.name }));
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSignature = (fieldId: string) => {
    setSignatures(prev => ({ ...prev, [fieldId]: true }));
    setFormData(prev => ({ ...prev, [fieldId]: CURRENT_USER.name }));
  };

  const handleSubmit = () => {
    const template = FORM_TEMPLATES.find(f => f.id === activeForm);
    if (!template) return;

    const newSubmission: FormSubmission = {
      id: `sub-${Date.now()}`,
      templateId: template.id,
      templateTitle: template.title,
      submittedBy: CURRENT_USER.name,
      submittedAt: new Date(),
      data: { ...formData }
    };

    setSubmissions(prev => [newSubmission, ...prev]);
    setSubmitSuccess(true);

    setTimeout(() => {
      setSubmitSuccess(false);
      setActiveForm(null);
      setFormData({});
      setPhotos({});
      setSignatures({});
    }, 2000);
  };

  const downloadPDF = (submission: FormSubmission) => {
    const content = `
FORM SUBMISSION REPORT
======================
Form: ${submission.templateTitle}
Submitted By: ${submission.submittedBy}
Date: ${submission.submittedAt.toLocaleString()}

DATA:
${Object.entries(submission.data).map(([key, value]) => `- ${key}: ${value}`).join('\n')}

---
Generated by BuildTrack
Acme Construction - North Salt Lake, UT
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${submission.templateTitle.replace(/\s+/g, '-')}-${submission.submittedAt.toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Create New Form Modal
  const CreateFormModal = () => (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={() => setShowCreateModal(false)}>
      <div className="bg-white dark:bg-slate-800 rounded-xl shadow-2xl w-full max-w-md" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between p-4 border-b border-slate-200 dark:border-slate-700">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">Create New Form</h2>
          <button onClick={() => setShowCreateModal(false)} className="p-1 hover:bg-slate-100 dark:hover:bg-slate-700 rounded">
            <X size={20} className="text-slate-500" />
          </button>
        </div>
        <div className="p-4">
          <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">
            Select a template to start a new form:
          </p>
          <div className="space-y-2">
            {FORM_TEMPLATES.map(template => (
              <button
                key={template.id}
                onClick={() => {
                  setShowCreateModal(false);
                  setActiveForm(template.id);
                }}
                className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 text-left"
              >
                <div className="w-10 h-10 bg-primary-50 dark:bg-slate-700 text-primary-600 dark:text-primary-400 rounded-lg flex items-center justify-center">
                  <FileText size={20} />
                </div>
                <div>
                  <p className="font-medium text-slate-900 dark:text-white">{template.title}</p>
                  <p className="text-xs text-slate-500 dark:text-slate-400">{template.fields.length} fields</p>
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );

  // Active Form View
  if (activeForm) {
    const template = FORM_TEMPLATES.find(f => f.id === activeForm);
    if (!template) return null;

    if (submitSuccess) {
      return (
        <div className="max-w-2xl mx-auto bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700 p-8 text-center">
          <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
            <Check size={32} className="text-green-600" />
          </div>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Form Submitted!</h2>
          <p className="text-slate-500 dark:text-slate-400">{template.title} has been submitted successfully.</p>
        </div>
      );
    }

    return (
      <div className="max-w-2xl mx-auto bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700 overflow-hidden">
        <div className="bg-secondary-500 p-4 text-white flex items-center gap-3">
          <button onClick={() => { setActiveForm(null); setFormData({}); setPhotos({}); setSignatures({}); }} className="hover:bg-white/10 p-1 rounded">
            <ChevronRight className="rotate-180" />
          </button>
          <h2 className="font-bold text-lg">{template.title}</h2>
        </div>

        <div className="p-6 space-y-6">
          {template.fields.map(field => (
            <div key={field.id} className="space-y-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                {field.label} {field.required && <span className="text-red-500">*</span>}
              </label>

              {field.type === 'text' && (
                <input
                  type="text"
                  value={formData[field.id] || ''}
                  onChange={(e) => handleFieldChange(field.id, e.target.value)}
                  className="w-full p-3 rounded-lg border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-900 focus:ring-2 focus:ring-primary-500 outline-none transition-all text-slate-900 dark:text-white"
                />
              )}

              {field.type === 'number' && (
                <input
                  type="number"
                  value={formData[field.id] || ''}
                  onChange={(e) => handleFieldChange(field.id, e.target.value)}
                  className="w-full p-3 rounded-lg border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-900 focus:ring-2 focus:ring-primary-500 outline-none transition-all text-slate-900 dark:text-white"
                />
              )}

              {field.type === 'yesno' && (
                <div className="flex gap-4">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name={field.id}
                      checked={formData[field.id] === 'yes'}
                      onChange={() => handleFieldChange(field.id, 'yes')}
                      className="w-4 h-4 text-primary-500"
                    />
                    <span className="text-slate-700 dark:text-slate-300">Yes</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name={field.id}
                      checked={formData[field.id] === 'no'}
                      onChange={() => handleFieldChange(field.id, 'no')}
                      className="w-4 h-4 text-primary-500"
                    />
                    <span className="text-slate-700 dark:text-slate-300">No</span>
                  </label>
                </div>
              )}

              {field.type === 'photo' && (
                <div>
                  <input
                    type="file"
                    ref={el => fileInputRefs.current[field.id] = el}
                    onChange={(e) => handlePhotoUpload(field.id, e)}
                    accept="image/*"
                    className="hidden"
                  />
                  {photos[field.id] ? (
                    <div className="relative">
                      <img src={photos[field.id]} alt="Uploaded" className="w-full h-48 object-cover rounded-lg" />
                      <button
                        onClick={() => {
                          setPhotos(prev => { const n = {...prev}; delete n[field.id]; return n; });
                          setFormData(prev => { const n = {...prev}; delete n[field.id]; return n; });
                        }}
                        className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full"
                      >
                        <X size={16} />
                      </button>
                    </div>
                  ) : (
                    <div
                      onClick={() => fileInputRefs.current[field.id]?.click()}
                      className="border-2 border-dashed border-slate-300 dark:border-slate-600 rounded-lg p-6 flex flex-col items-center justify-center text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900/50 transition-colors cursor-pointer"
                    >
                      <Camera size={24} className="mb-2" />
                      <span className="text-sm">Tap to capture or upload</span>
                    </div>
                  )}
                </div>
              )}

              {field.type === 'signature' && (
                <div
                  onClick={() => handleSignature(field.id)}
                  className={`h-32 border rounded-lg flex items-center justify-center cursor-pointer transition-colors ${
                    signatures[field.id]
                      ? 'bg-green-50 dark:bg-green-900/20 border-green-300 dark:border-green-700'
                      : 'bg-slate-50 dark:bg-slate-900 border-slate-200 dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800'
                  }`}
                >
                  {signatures[field.id] ? (
                    <div className="text-center">
                      <p className="font-script text-2xl text-slate-900 dark:text-white">{CURRENT_USER.name}</p>
                      <p className="text-xs text-green-600 dark:text-green-400 mt-1">Signed</p>
                    </div>
                  ) : (
                    <span className="text-slate-400 italic">Tap to sign</span>
                  )}
                </div>
              )}
            </div>
          ))}

          <div className="pt-4">
            <button
              onClick={handleSubmit}
              className="w-full bg-primary-500 hover:bg-primary-600 text-white font-bold py-4 rounded-lg shadow-lg flex items-center justify-center gap-2 transition-transform active:scale-95"
            >
              <Send size={18} /> Submit Form
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Field Forms</h2>
        <button
          onClick={() => setShowCreateModal(true)}
          className="bg-secondary-500 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-secondary-600"
        >
          <Plus size={16} /> Create New
        </button>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {FORM_TEMPLATES.map(form => (
          <div
            key={form.id}
            onClick={() => setActiveForm(form.id)}
            className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 cursor-pointer hover:border-primary-500 transition-colors group"
          >
            <div className="w-10 h-10 bg-primary-50 dark:bg-slate-700 text-primary-600 dark:text-primary-400 rounded-lg flex items-center justify-center mb-4 group-hover:bg-primary-500 group-hover:text-white transition-colors">
              <FileText size={20} />
            </div>
            <h3 className="font-bold text-slate-900 dark:text-white mb-1">{form.title}</h3>
            <p className="text-sm text-slate-500 dark:text-slate-400">{form.fields.length} fields</p>
          </div>
        ))}
      </div>

      <div className="mt-8">
        <h3 className="font-bold text-slate-900 dark:text-white mb-4">Recent Submissions</h3>
        <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
          {submissions.map((submission) => (
            <div key={submission.id} className="flex items-center justify-between p-4 border-b border-slate-100 dark:border-slate-700 last:border-0 hover:bg-slate-50 dark:hover:bg-slate-700/50">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 flex items-center justify-center text-xs font-bold">
                  {submission.submittedBy.split(' ').map(n => n[0]).join('')}
                </div>
                <div>
                  <p className="text-sm font-medium text-slate-900 dark:text-white">{submission.templateTitle}</p>
                  <p className="text-xs text-slate-500 dark:text-slate-400">
                    Submitted by {submission.submittedBy} • {formatTimeAgo(submission.submittedAt)}
                  </p>
                </div>
              </div>
              <button
                onClick={() => downloadPDF(submission)}
                className="text-secondary-600 dark:text-secondary-400 hover:underline text-sm font-medium flex items-center gap-1"
              >
                <Download size={14} /> View PDF
              </button>
            </div>
          ))}
        </div>
      </div>

      {showCreateModal && <CreateFormModal />}
    </div>
  );
};
